### ISSUE TITLE
Installing on Hydro fails

### ISSUE THREAD

**Issue by zoltan-fedor** [epsilonorion/roscopter#2]
I'm trying to install it on Hydro following the install options, but when I get to the
"To build mavlink, navigate to the "pymavlink" folder and run the command "sudo python setup.py install"."
Then while mavlink seemingly compiles after restarting there is no ROS anymore, catkin_make, roscore, etc all returns command not found.

**Comment by tonybaltovski** [comment]
Did you initiate the submodule?

**Comment by zoltan-fedor** [comment]
It seems I just managed to figure out - see issue http://answers.ros.org/question/127971/compiling-new-package-causing-roscore-command-not-found/?answer=128366
It looks I was following the Hydro install instructions too closely and when checked out mavlink the folder got created in the roscopter folder instead of roscopter/src.

Could I suggest an addition to the Hydro install instructions specifying that you need to go to the src folder before checking out mavlink?

**Comment by tonybaltovski** [comment]
Did you get it to work?

**Comment by zoltan-fedor** [comment]
Yes, the roscopter install did work after placing mavlink into the roscopter/src folder and compiling mavlink there, but now I get "no module mavutil" when running:
rosrun roscopter driver.py  --device=/dev/ttyACM0 --baudrate=115200
Traceback (most recent call last):
  File "/home/ilagi/ros_catkin_ws/install_isolated/lib/roscopter/driver.py", line 47, in <module>
    import mavutil
ImportError: No module named mavutil

So something is wrong with the mavlink install.

**Comment by tonybaltovski** [comment]
Try my branch.  I get that error when I install the package via catkin_make install.  When I do catkin_make and only source the devel/setup.bash it works.

**Comment by zoltan-fedor** [comment]
Sorry, I have looked at the python code where it was throwing this reference error and it was referring to the mavlink library relatively as "../mavlink/pymavlink", so I copied the whole mavlink library to install_isolated/lib => no more error message.
Now it is only an OS error permission denied on /dev/ttyACM0, but that should be just the APM being on a different USB or something.

**Comment by tonybaltovski** [comment]
Assuming you are using Ubuntu, you don't have permissions for dialout.  Either add yourself to the group or do sudo chmod 777 /dev/ttyACM0.  It will be most likely on /dev/ttyACMx but the number may change.

**Comment by zoltan-fedor** [comment]
Thanks, I was just writing that I just did that (chmod 777) and now I see "Waiting for APM heartbeat"
Yippie! It seems it is working!
Now I just figure out why I never receive a heartbeat from APM.
Thanks for all the help.

Ps.: I'm doing all this on a Raspberry Pi connected to an APM on a quadcopter.

**Comment by tonybaltovski** [comment]
No worries.  Did you update to lasted APM code?

I am going towards that or a Beaglebone black but I am using a desktop currently till I get the control working.

**Comment by zoltan-fedor** [comment]
I was using a custom controller before from here (http://ghowen.me/build-your-own-quadcopter-autopilot/), maybe that caused not receiving the heartbeat.
I have reloaded firmware version 3.1 and now I got the heartbeat.

Now I'm trying to arm but "rosservice list" doesn't show a /roscopter/arm service.
driver.py is showing the below messages, if I read it right there is no arming because the RC not being calibrated. Unfortunately I have no RC, I'm going to control it only from the Raspberry, so now I try to somehow get over RC calibration with the Mission Planner to stop the lack of RC calibration prevent arming.

The suggestion her (https://github.com/tridge/MAVProxy/issues/11) to set the RC3_MIN parameter to 1101. Can we set parameters with roscopter? I couldn't find any reference to parameters in the source code, but maybe I missed it.

driver.py messages:
rosrun roscopter driver.py  --device=/dev/ttyACM0 --baudrate=115200
Waiting for APM heartbeat
Heartbeat from APM (system 1 component 1)
Sleeping for 10 seconds to allow system, to be ready
Sending all stream request for rate 10
Clear Waypoints
STATUSTEXT: Status severity is 1. Text Message is barometer calibration complete
STATUSTEXT: Status severity is 1. Text Message is GROUND START
Init Gyro*STATUSTEXT: Status severity is 1. Text Message is Initialising APM...

## *INS

G_off: -0.02, -0.02, 0.02
A_off: -0.06, 0.25, 0.58
A_scale: 0.99, 0.99, 0.98

Ready to FLY MISSION_ACK: Mission Message ACK with response - 0
MISSION_ACK: Mission Message ACK with response - 0
MISSION_ACK: Mission Message ACK with response - 0
STATUSTEXT: Status severity is 3. Text Message is PreArm: RC not calibrated
STATUSTEXT: Status severity is 3. Text Message is PreArm: RC not calibrated
~*.<j >?#STATUSTEXT: Status severity is 3. Text Message is PreArm: RC not calibrated
i2'A)0,(LLLL4VJVSTATUSTEXT: Status severity is 3. Text Message is PreArm: RC not calibrated
STATUSTEXT: Status severity is 3. Text Message is PreArm: RC not calibrated
STATUSTEXT: Status severity is 3. Text Message is PreArm: RC not calibrated
STATUSTEXT: Status severity is 3. Text Message is PreArm: RC not calibrated

**Comment by tonybaltovski** [comment]
That's pretty interesting.  I'm going towards indoor autonomous flight.

You can disable the PreArm using the apm planner or anything that can write MAVLink params, it is called ARMING_CHECK = 0.

**Comment by zoltan-fedor** [comment]
Yes, I have removed arming_check with the planner and now it arms fine - see below.
Unfortunately my quad is far to big for indoor flying, so for now outdoor only, but autonomous flight is the end goal. The next big step is to get stereo vision working to be able to discover the surroundings and use ROS to create autonomous path planning.

rosrun roscopter driver.py  --device=/dev/ttyACM0 --baudrate=115200
Waiting for APM heartbeat
Heartbeat from APM (system 1 component 1)
Sleeping for 10 seconds to allow system, to be ready
Sending all stream request for rate 10
Clear Waypoints
STATUSTEXT: Status severity is 1. Text Message is barometer calibration complete
STATUSTEXT: Status severity is 1. Text Message is GROUND START
Init Gyro*STATUSTEXT: Status severity is 1. Text Message is Initialising APM...

## *INS

G_off: -0.02, -0.02, 0.02
A_off: -0.06, 0.12, 0.63
A_scale: 0.99, 0.98, 0.98

Ready to FLY L=

**Comment by epsilonorion** [comment]
Sorry I missed the problem you guys were having.  Are you guys still having problems with the MavLink setup.  I haven't had any problems with setting up on Hydro or Groovy.  I want to make sure I make any changes that are needed for this repository to fully work with any setup.

**Comment by zoltan-fedor** [comment]
Thanks, it works now, I can arm it.
Now I'm trying to get the manual RC overwrite to work, with no luck for now. No error message, just no reaction from the motors:
rostopic pub -1 send_rc roscopter/RC "{channel:[1000,1000,1200,1000,1000,1000,1000,1000]}"

**Comment by tonybaltovski** [comment]
\What command do you run to start the roscopter node?

**Comment by zoltan-fedor** [comment]
I use
rosrun roscopter driver.py  --device=/dev/ttyACM0 --baudrate=115200 --enable-rc-control=True

**Comment by zoltan-fedor** [comment]
It seems it was only a timing issue when manually issuing the RC commands via ros publish. Now that I have created a node to send RC commands from an Android app emulating an RC it seems to be working fine. What is kind of a surprise that after arming I have only a few seconds to start sending RC commands, otherwise the motors stop and don't start again until the next arming.
If you are interested to see my remote RC control with an Android app then you can find in my fork:https://github.com/evk02/roscopter
The Android app is taken from http://ghowen.me/build-your-own-quadcopter-autopilot/

**Comment by epsilonorion** [comment]
Very nice.  Glad it worked.  The motor stop is due to either the APMCopter
software or the esc's disarming due to no activity.  It is typically
between 5 and 10 seconds.

I will definitely take a look at the app.  Currently I have a teleop
program that can drive the roscopter using an XBox controller.  I also have
a full fledged Android Mission Control App to fly vehicles such as APM
vehicles.

**Comment by zoltan-fedor** [comment]
Thanks.
That Mission Control App for Android you mentioned is the Droidplanner or something else?
Is this something what can communicate the vehicle while in the air?

**Comment by epsilonorion** [comment]
There are two versions I currently have.

The first communicated with the vehicle using ROSJava.  It allowed mission
planning and control on and off the ground.  It also streamed video and
target recognition data back to the tablet. This version is slightly
defunct at the moment as ROSJava has changed quite a bit since the first
creation.

The second and more recent version moves away from ROSJava to benefit from
using XBee devices for better range.  The application connects to a IOIO
board and handles communications with one or more vehicles.  This is part
of a bigger project I am building that acts as a base station for
communicating with multiple air and ground vehicles running any type of
autopilot (APM, ASCTEC, etc).  It allows a MultiMaster system built into
XBee comms, removing the limitations of ROSJava and wireless.

Does your app use ROSJava?

**Comment by zoltan-fedor** [comment]
Actually I put ROS on a Raspberry and connected that to the Ardupilot directly via USB which flies together, so I have a wide range of options for communications when it comes to communicating with ROS running on the Raspberry. Currently using wifi, but planning to add 3g card, radio (maybe XBee) so when it goes out of range then it will just switch to a different comm channel, otherwise goes to autonomous mode.
Currently I use just a standard socket connection via wifi to connect to this ROS RC node on the Raspberry, which then hands over the RC commands to the roscopter node.

**Comment by epsilonorion** [comment]
Very nice.

I am actually doing something similar.  I have ROS on an ODroid which is
connected to the APM via USB.  It handles all high level controls between
autonomous or RC control.  My original app used 3g or WiFi.  Worked great,
but can definitely see the slow rate with the 3g occasionally.

Have since moved to the XBee for ease of use and expansion for multiple
vehicles to be used at a single time.

**Comment by zoltan-fedor** [comment]
Interesting. What range and bandwidth did you get from XBee?

**Comment by ravikishorem** [comment]
Hi,
I am trying to control my APM2.5 with ros, I followed the instructions word to word and i got everything, but at the final step I have given the following command: rosrun roscopter roscopter.py --device=/dev/ttyACM0 --baudrate=115200 in the terminal but I am getting the following message: 
ravi@ravi-H61M-D2-B3:~/Downloads/roscopter/src/mavlink$ nodes/roscopter.py --device=/dev/ttyACM0 --baudrate=115200Traceback (most recent call last):
  File "nodes/roscopter.py", line 2, in <module>
    import roslib; roslib.load_manifest('roscopter')
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslib/launcher.py", line 62, in load_manifest
    sys.path = _generate_python_path(package_name, _rospack) + sys.path
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslib/launcher.py", line 93, in _generate_python_path
    m = rospack.get_manifest(pkg)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 159, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 198, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 190, in get_path
    raise ResourceNotFound(name, ros_paths=self._ros_paths)
rospkg.common.ResourceNotFound: roscopter
ROS path [0]=/opt/ros/groovy/share/ros
ROS path [1]=/opt/ros/groovy/share
ROS path [2]=/opt/ros/groovy/stacks
ravi@ravi-H61M-D2-B3:~/Downloads/roscopter/src/mavlink$ 

Please help me to figure out this problem. If I missed anything then let me know.
Thanks in advance.

**Comment by epsilonorion** [comment]
It looks as if you are using Groovy.  Did you confirm that you moved the
branch of roscopter to Groovy (see below)?  If so, you will notice there is
a slight difference.  The nodes folder has been moved to scripts.  The
roscopter.py file has been changed to driver.py.  I have updated the wiki
to represent this as it was a little out of date.

Also, you display two ways of running the app: 1) using rosrun 2)using the
direct method.  The first option wouldn't work if you are on Groovy as
roscopter.py has changed to driver.py.  The second method wouldn't work
partially for the same reason, however, even if you used the correct names
it still wouldn't work.  The second method directly runs the script without
the assistance of rosrun.  This means you should be in the main package
directory (roscopter) not mavlink.  The correct was in Groovy would be
scripts/driver.py

Finally, and more related to your problem, it does seem that you are using
the Fuerte branch instead of the Groovy branch since the error seems to
find the correct "older" nodes/roscopter.py file.  Are you sure that you
have the workspace setup correctly having roscopter in the Downloads
folder?  Have you built roscopter, as it does include messages and services
for ROS that are needed for the code to work.  The files seems to be having
a problem locating your ros and roscopter folders.

**Comment by ravikishorem** [comment]
Hi Epsilonorian,
   I changed the ros path to groovy by following the link: http://wiki.ros.org/ROS/Tutorials/NavigatingTheFilesystem

After that I started doing it from the beginning, but I got this error: 
ravi@ravi-H61M-D2-B3:~/catkin_ws$ catkin_make_isolated --pkg roscopter --installBase path: /home/ravi/catkin_ws
Source space: /home/ravi/catkin_ws/src
Build space: /home/ravi/catkin_ws/build_isolated
Devel space: /home/ravi/catkin_ws/devel_isolated
Install space: /home/ravi/catkin_ws/install_isolated

```
~~  traversing 1 packages in topological order:
~~  - roscopter
```

==> Processing catkin package: 'roscopter'
==> cmake /home/ravi/catkin_ws/src/roscopter -DCATKIN_DEVEL_PREFIX=/home/ravi/catkin_ws/devel_isolated/roscopter -DCMAKE_INSTALL_PREFIX=/home/ravi/catkin_ws/install_isolated in '/home/ravi/catkin_ws/build_isolated/roscopter'
CMake Error: The current CMakeCache.txt directory /home/ravi/catkin_ws/src/roscopter/CMakeCache.txt is different than the directory /home/ravi/Downloads/roscopter where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
<== Failed to process package 'roscopter': 
  Command 'cmake /home/ravi/catkin_ws/src/roscopter -DCATKIN_DEVEL_PREFIX=/home/ravi/catkin_ws/devel_isolated/roscopter -DCMAKE_INSTALL_PREFIX=/home/ravi/catkin_ws/install_isolated' returned non-zero exit status 1

Reproduce this error by running:
==> cd /home/ravi/catkin_ws/build_isolated/roscopter && cmake /home/ravi/catkin_ws/src/roscopter -DCATKIN_DEVEL_PREFIX=/home/ravi/catkin_ws/devel_isolated/roscopter -DCMAKE_INSTALL_PREFIX=/home/ravi/catkin_ws/install_isolated

Command failed, exiting.
ravi@ravi-H61M-D2-B3:~/catkin_ws$ 

Actually I am new to ROS, if you don't mind can you please help me to complete this and also can you please elaborate it and can you send the same to  ravi.kishore674@gmail.com please??
