### ISSUE TITLE
IMU data cannot be published

### ISSUE THREAD

**Issue by lanyusea** [epsilonorion/roscopter#7]
I run `rosrun roscopter imu_transform_publish.py` but failed today.
It worked well before and I didn't change any file related to roscopter package..

The error is 

``` python
[ERROR] [WallTime: 1401205871.351031] bad callback: <function imu_callback at 0x13e8578>
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/topics.py", line 682, in _invoke_callback
    cb(msg)
  File "/home/aqua/ros_catkin/src/roscopter/scripts/imu_transform_publish.py", line 74, in imu_callback
    q = tf.transformations.quaternion_from_euler(roll,pitch,yaw)
AttributeError: 'module' object has no attribute 'transformations'
```

no idea how to solve that currently....

**Comment by lanyusea** [comment]
solved without knowing why this issue happened today...

download the tf [repo](https://github.com/ros/geometry/tree/hydro-devel/tf) to your workspace and build one by yourself...
